name: CI/CD for Evoker bot

on:
  push:
    branches:
      - develop
      - feature/awakeMode

jobs:
  install-and-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Package the application
        run: mvn clean package -DskipTests

      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг для входа в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Шаг для сборки и пуша Docker-образа с Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/evoker-bot:latest
          build-args: JAR_FILE=${{ github.workspace }}/target/app.jar