name: CI/CD for Evoker bot

on:
  push:
    branches:
      - develop
      - feature/awakeMode

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn clean install -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: install-and-build
    steps:
      - name: Run tests
        env:
          BOT_NAME: ${{ secrets.BOT_NAME }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          mvn test

